"""
llm_analyzer.py  —  OpenAI-powered threat analysis + graceful fallback.
If the OpenAI key is invalid / over quota, the system generates a rich
rule-based report so the dashboard never shows a bare error message.
"""

import os
from rag.knowledge_base import get_kb

# ── severity colour helpers ──────────────────────────────────────────────────
SEVERITY_MAP = {
    "DoS": ("Critical", "🔴"),
    "BruteForce": ("High", "🟠"),
    "PortScan": ("Medium", "🟡"),
    "SQLInjection": ("Critical", "🔴"),
    "Backdoor": ("Critical", "🔴"),
    "Benign": ("None", "🟢"),
}

MITIGATION_MAP = {
    "DoS":          "Enable SYN cookies, rate-limit inbound SYN packets, deploy a DDoS scrubbing service (Cloudflare / AWS Shield).",
    "BruteForce":   "Block the source IP with fail2ban, enforce key-based SSH auth, disable password login, enable MFA.",
    "PortScan":     "Drop unsolicited SYN packets via firewall, enable port-knock, segment the network, alert on probe frequency.",
    "SQLInjection": "Deploy a WAF (e.g. ModSecurity), audit application code for parameterised queries, use least-privilege DB accounts.",
    "Backdoor":     "Isolate the host immediately, inspect running processes, perform memory forensics, scan for C2 IOCs, re-image if confirmed.",
    "Benign":       "No action required. Continue normal monitoring.",
}


def _fallback_report(record: dict, prediction: dict) -> str:
    """Rich rule-based threat report — used when OpenAI is unavailable."""
    ptype = prediction.get("prediction", "Unknown")
    conf  = prediction.get("confidence", 0)
    sev, icon = SEVERITY_MAP.get(ptype, ("Unknown", "⚪"))
    mitigation = MITIGATION_MAP.get(ptype, "Review manually.")

    kb = get_kb()
    rag_entries = kb.retrieve(ptype, top_k=1)
    detail = rag_entries[0]["description"] if rag_entries else "No additional threat intelligence available."

    if ptype == "Benign":
        return (
            f"### {icon} Traffic Classification: Benign\n\n"
            f"The ML model classified this flow as **benign** with **{conf}% confidence**. "
            f"The traffic characteristics — destination port {record.get('dst_port')}, "
            f"protocol {record.get('protocol')}, packet count {record.get('packet_count')} — "
            f"are consistent with normal network activity.\n\n"
            f"**Recommended Action:** Continue routine monitoring. No immediate response required."
        )

    return (
        f"### {icon} Threat Detected: **{ptype}** (Severity: {sev})\n\n"
        f"**Confidence:** {conf}%\n\n"
        f"**What this pattern indicates:**\n"
        f"{detail}\n\n"
        f"**Observable indicators in this flow:**\n"
        f"- Source: `{record.get('src_ip')}:{record.get('src_port')}` → "
        f"Destination: `{record.get('dst_ip')}:{record.get('dst_port')}`\n"
        f"- Protocol: `{record.get('protocol')}` | Flag: `{record.get('flag')}`\n"
        f"- Packets: `{record.get('packet_count')}` | Bytes: `{record.get('byte_count')}` | "
        f"Duration: `{record.get('duration_ms')} ms` | Rate: `{record.get('packets_per_sec')} pkt/s`\n\n"
        f"**Potential impact:**\n"
        f"If confirmed, this attack could lead to service disruption, unauthorized access, "
        f"or data exfiltration depending on whether the attacker achieves their objective.\n\n"
        f"**Immediate response actions:**\n"
        f"{mitigation}\n\n"
        f"**Long-term prevention:**\n"
        f"Implement network segmentation, enforce least-privilege access policies, "
        f"deploy a SIEM solution for continuous monitoring, and schedule regular penetration testing.\n\n"
        f"> *Note: This report was generated by the rule-based fallback engine. "
        f"Add a valid OpenAI API key for GPT-4o-powered analysis.*"
    )


def _openai_report(record: dict, prediction: dict, api_key: str) -> str:
    from openai import OpenAI
    kb = get_kb()
    ptype = prediction.get("prediction", "Unknown")
    rag_entries = kb.retrieve(
        f"{ptype} port {record.get('dst_port')} protocol {record.get('protocol')} flag {record.get('flag')}",
        top_k=2,
    )
    rag_context = kb.format_context_for_llm(rag_entries)

    prompt = f"""You are an expert cybersecurity analyst reviewing an IDS alert.

## Traffic Record
- Src: {record.get('src_ip')}:{record.get('src_port')}  →  Dst: {record.get('dst_ip')}:{record.get('dst_port')}
- Protocol: {record.get('protocol')} | Flag: {record.get('flag')}
- Packets: {record.get('packet_count')} | Bytes: {record.get('byte_count')}
- Duration: {record.get('duration_ms')} ms | Rate: {record.get('packets_per_sec')} pkt/s

## ML Prediction
- Threat: {ptype} ({prediction.get('confidence')}% confidence)

## Threat Intelligence
{rag_context}

Write a 4-paragraph professional security analyst report covering:
1. What the traffic pattern indicates
2. Threat severity and likely attack vector
3. Potential impact
4. Immediate + long-term mitigation steps

Use clear English suitable for both technical and non-technical readers."""

    client = OpenAI(api_key=api_key)
    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are a senior SOC analyst specializing in intrusion detection."},
            {"role": "user",   "content": prompt},
        ],
        temperature=0.3,
        max_tokens=700,
    )
    return resp.choices[0].message.content


def analyze_threat(record: dict, prediction: dict) -> str:
    api_key = os.getenv("OPENAI_API_KEY", "")
    if api_key and len(api_key) > 20:
        try:
            return _openai_report(record, prediction, api_key)
        except Exception as e:
            return _fallback_report(record, prediction) + f"\n\n*(OpenAI error: {e})*"
    return _fallback_report(record, prediction)


# ── Batch summarizer ─────────────────────────────────────────────────────────

def _fallback_summary(alerts: list) -> str:
    from collections import Counter
    counts = Counter(a.get("prediction", "Unknown") for a in alerts)
    threat_counts = {k: v for k, v in counts.items() if k != "Benign"}
    benign_count = counts.get("Benign", 0)
    total = len(alerts)

    lines = [f"**Alert Summary — {total} events analysed**\n"]
    if threat_counts:
        top_threat = max(threat_counts, key=threat_counts.get)
        lines.append(
            f"The network is under **active threat activity**. "
            f"Out of {total} events, **{sum(threat_counts.values())} were classified as malicious** "
            f"and {benign_count} as benign.\n"
        )
        lines.append("**Threat breakdown:**")
        for t, c in sorted(threat_counts.items(), key=lambda x: -x[1]):
            sev, icon = SEVERITY_MAP.get(t, ("Unknown", "⚪"))
            lines.append(f"- {icon} **{t}**: {c} alerts (Severity: {sev})")
        lines.append(f"\n**Top priority:** Address **{top_threat}** attacks immediately. "
                     f"{MITIGATION_MAP.get(top_threat, '')}")
        lines.append("\n**Recommended actions for the security team:**\n"
                     "1. Block top attacker IPs at the perimeter firewall\n"
                     "2. Review authentication logs for successful breaches\n"
                     "3. Escalate Critical-severity events to the incident response team\n"
                     "4. Enable enhanced logging on affected services\n"
                     "> *Add a valid OpenAI API key for GPT-4o executive summaries.*")
    else:
        lines.append(f"All {total} analysed events appear to be **benign**. No immediate action required.")

    return "\n".join(lines)


def summarize_alerts_batch(alerts: list) -> str:
    api_key = os.getenv("OPENAI_API_KEY", "")
    if not alerts:
        return "No alerts to summarize."
    if api_key and len(api_key) > 20:
        try:
            from openai import OpenAI
            client = OpenAI(api_key=api_key)
            from collections import Counter
            counts = Counter(a.get("prediction") for a in alerts)
            alert_lines = "\n".join(
                f"{i+1}. [{a.get('timestamp','?')}] {a.get('prediction')} ({a.get('confidence',0)}%) "
                f"Src:{a.get('src_ip','?')} → Port {a.get('dst_port','?')}"
                for i, a in enumerate(alerts[:20])
            )
            resp = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "You are a SOC analyst writing executive summaries."},
                    {"role": "user", "content": (
                        f"Recent IDS alerts:\n{alert_lines}\n\n"
                        f"Breakdown: {dict(counts)}\n\n"
                        "Write a 3-paragraph executive summary: current threat landscape, "
                        "critical threats needing attention, and recommended priority actions."
                    )},
                ],
                temperature=0.3, max_tokens=500,
            )
            return resp.choices[0].message.content
        except Exception as e:
            return _fallback_summary(alerts) + f"\n\n*(OpenAI error: {e})*"
    return _fallback_summary(alerts)


# ── Security assistant chat ───────────────────────────────────────────────────

CANNED_RESPONSES = {
    "syn": "A **SYN flood** is a DoS attack that exploits TCP's 3-way handshake. The attacker sends many SYN packets without completing the connection, exhausting server resources. **Mitigate** with SYN cookies (`net.ipv4.tcp_syncookies=1`), rate limiting, and a CDN/DDoS scrubber.",
    "port scan": "**Port scanning** probes ports to find open services. Nmap is the most common tool. **Detect** via high connection rates to varied ports from one source. **Prevent** with firewall rules, port-knocking, and IDS alerts.",
    "sql": "**SQL Injection** embeds SQL in HTTP parameters to manipulate databases. At the network level it looks like HTTP traffic to port 80/443 with anomalous payload sizes. **Prevent** with a WAF, parameterised queries, and input validation.",
    "backdoor": "**Backdoor/C2 beaconing** creates persistent connections on non-standard ports (4444, 8888). Characteristics: long duration, low packet rate, encrypted payload. **Respond** by isolating the host, inspecting processes, and checking threat-intel feeds.",
    "brute": "**Brute force** attacks repeatedly try credentials against SSH (22), FTP (21), or RDP (3389). **Detect** via repeated connection attempts from the same IP. **Block** with fail2ban, account lockout, and key-based auth.",
}


def chat_with_security_assistant(user_message: str, conversation_history: list):
    api_key = os.getenv("OPENAI_API_KEY", "")
    if api_key and len(api_key) > 20:
        try:
            from openai import OpenAI
            kb = get_kb()
            rag_entries = kb.retrieve(user_message, top_k=2)
            rag_context = kb.format_context_for_llm(rag_entries)
            system_prompt = (
                "You are an intelligent cybersecurity assistant for an IDS dashboard. "
                "Help analysts understand alerts, threats, and mitigations.\n\n"
                f"Current Threat Intelligence:\n{rag_context}"
            )
            messages = [{"role": "system", "content": system_prompt}]
            messages.extend(conversation_history[-10:])
            messages.append({"role": "user", "content": user_message})
            client = OpenAI(api_key=api_key)
            resp = client.chat.completions.create(
                model="gpt-4o-mini", messages=messages,
                temperature=0.5, max_tokens=600,
            )
            reply = resp.choices[0].message.content
        except Exception as e:
            reply = _canned_reply(user_message) + f"\n\n*(OpenAI unavailable: {e})*"
    else:
        reply = _canned_reply(user_message)

    conversation_history.append({"role": "user",      "content": user_message})
    conversation_history.append({"role": "assistant", "content": reply})
    return reply, conversation_history


def _canned_reply(msg: str) -> str:
    msg_lower = msg.lower()
    for kw, resp in CANNED_RESPONSES.items():
        if kw in msg_lower:
            return resp + "\n\n> *Add a valid OpenAI API key for full GPT-4o-powered responses.*"
    return (
        "I'm the rule-based security assistant. I can answer questions about: "
        "**SYN flood, port scanning, SQL injection, brute force, backdoor/C2 attacks**.\n\n"
        "Add a valid OpenAI API key for full AI-powered conversations."
    )
